name: Build Royal Spin APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.0'
          channel: stable

      - name: Install dependencies
        run: flutter pub get
      - name: Create Android project
        run: flutter create --platforms=android .
      - name: Update Kotlin version
        run: sed -i 's/id("org.jetbrains.kotlin.android") version "2.1.0"/id("org.jetbrains.kotlin.android") version "2.3.0"/' android/settings.gradle.kts
      - name: Fix Kotlin compiler options
        run: |
            sed -i '/kotlinOptions {/,/}/c\    kotlin {\n        compilerOptions {\n            jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_11\n        }\n    }' android/app/build.gradle.kts
      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: royal-spin-apk
          path: build/app/outputs/flutter-apk/app-release.apk
